language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
sudo: false
before_install:
  - export PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - pip install -r requirements.txt
install:
  - python setup.py install
script:
  - pep8 .
  - pyflakes .
  - py.test -v
